In [29]:

import matplotlib.pyplot as plt
import numpy as np

x = np.float32(1.0)
print(x)

y = np.int_([1,2,4])
print(y)

z = np.arange(4, dtype=np.uint8)
print(z)
z.dtype

z.astype(float)

xyz= np.array(np.random.random((100,3)))
print(xyz)

xyz

new = xyz.reshape(xyz[:, 0], xyz[:, 1], xyz[:, 0]*xyz[:, 0], xyz[:, 1]*xyz[:, 1], xyz[:, 0]*xyz[:, 1], 1)
print(new)

#plt.scatter(xyz[:, 0], xyz[:, 1], c = xyz[:,2])
#plt.show()
#plt.scatter?

1.0
[1 2 4]
[0 1 2 3]
[[ 0.4473354   0.19938486  0.06202325]
 [ 0.91961954  0.61644248  0.16891973]
 [ 0.4846831   0.05533239  0.89976185]
 [ 0.05809907  0.34325042  0.01238725]
 [ 0.93607099  0.02836735  0.15275649]
 [ 0.43473361  0.05536793  0.64811439]
 [ 0.27804389  0.38449592  0.46087627]
 [ 0.2512249   0.71027302  0.19950321]
 [ 0.97427075  0.4168183   0.70802729]
 [ 0.31352945  0.3731052   0.42399058]
 [ 0.39668881  0.84738729  0.24202877]
 [ 0.8557031   0.53281019  0.62084195]
 [ 0.71748853  0.94984527  0.75561499]
 [ 0.55731418  0.89434255  0.72787566]
 [ 0.11934733  0.99165008  0.71565699]
 [ 0.79054958  0.02933364  0.7461064 ]
 [ 0.56390555  0.63165957  0.76972768]
 [ 0.01211836  0.98080351  0.80238172]
 [ 0.65880131  0.49934475  0.24721676]
 [ 0.42958347  0.03999545  0.67155518]
 [ 0.2734664   0.99291808  0.79918815]
 [ 0.58640718  0.09150733  0.31176021]
 [ 0.30452357  0.58353166  0.50892208]
 [ 0.80499839  0.95001249  0.66628606]
 [ 0.97288052  0.98792942  0.29151521]
 [ 

TypeError: only integer scalar arrays can be converted to a scalar index